### ISSUE TITLE
Functions with @liveUpdate only meta doesn't get into data.live

### ISSUE THREAD

**Issue by nibb13** [profelis/halk2#2]
Such function:
```
@liveUpdate function myMethod() {
	trace('Hello, World!');
}
```
will never pass LiveProcessor as its liveMeta will be always null and processLiveField will not be executed due to [LiveProcessor.hx:193](https://github.com/profelis/halk2/blob/e323eb5a53aa22efe68b80e5dff247db716b5190/src/halk/macro/LiveProcessor.hx#L193)

Is it a bug or halk2 requires both metas? ( i.e. `@liveUpdate @live function myMethod() {...` )

**Comment by profelis** [comment]
If you need `live` function, you should use both `@live @liveupdate`. LiveUpdate function can be nonlive, for example update some state, reload external files, etc.
